### ISSUE TITLE
点击开始后 会自动开始断开 再开始断开 无限循环

### ISSUE THREAD

**Issue by kafeixiang** [dyhkwong/Exclave#4]
SagerNet 0.8.2 (819) OSS
Date: 2023-10-20 23:22:06.290 UTC

OS_VERSION: 4.4.153-perf+
SDK_INT: 28
RELEASE: 9
ID: PKQ1.180904.001
DISPLAY: PKQ1.180904.001
INCREMENTAL: V12.0.3.0.PEICNXM
SECURITY_PATCH: 2020-11-05
IS_DEBUGGABLE: 0
IS_EMULATOR: null
IS_TREBLE_ENABLED: true
TYPE: user
TAGS: release-keys

MANUFACTURER: Xiaomi
BRAND: xiaomi
MODEL: Redmi Note 5
PRODUCT: whyred
BOARD: sdm636
HARDWARE: qcom
DEVICE: whyred
SUPPORTED_ABIS: arm64-v8a, armeabi-v7a, armeabi

Settings: 

socksPort: 2080
portLocalDns: 6450
httpPort: 9080
transproxyPort: 9200
dnsHosts0: 
remoteDns: tcp://1.1.1.1
directDns: tcp://223.5.5.5
mtu: 1500
isAutoConnect: true
acquireWakeLock: false
appTheme: 2
nightTheme: 0
serviceMode: vpn
tunImplementation: 1
appTrafficStatistics: false
profileTrafficStatistics: true
speedInterval: 1000
alwaysShowAddress: false
securityAdvisory: true
meteredNetwork: false
showDirectSpeed: false
allowAccess: false
proxyApps: false
bypassLan: false
bypassLanInCoreOnly: false
domainStrategy: AsIs
trafficSniffing: true
destinationOverride: false
resolveDestination: false
ipv6Mode: 1
rulesProvider: 0
providerTrojan: 0
providerRootCA: 0
useLocalDnsAsDirectDns: false
enableDnsRouting: true
enableFakeDns: false
hijackDns: false
requireHttp: true
appendHttpProxy: true
requireTransproxy: false
transproxyMode: 0
connectionTestURL: https://www.google.com/generate_204
enableMux: false
enableMuxForAll: false
muxConcurrency: 8
tcpKeepAliveInterval: 15
enablePcap: false
enableLog: true
profileGroup: 2
profileId: 1
profileCurrent: 1
profileStarted: 1

Thread: Thread[main,5,main]

java.lang.NoSuchMethodError: No direct method <init>(I)V in class Landroid/net/ConnectivityManager$NetworkCallback; or its super classes (declaration of 'android.net.ConnectivityManager$NetworkCallback' appears in /system/framework/framework.jar)
    at io.nekohasekai.sagernet.utils.DefaultNetworkListener$Callback.<init>(DefaultNetworkListener.kt:2)
    at io.nekohasekai.sagernet.utils.DefaultNetworkListener$Callback.<clinit>(DefaultNetworkListener.kt:3)
    at io.nekohasekai.sagernet.utils.DefaultNetworkListener.register(DefaultNetworkListener.kt:51)
    at io.nekohasekai.sagernet.utils.DefaultNetworkListener.access$register(DefaultNetworkListener.kt:1)
    at io.nekohasekai.sagernet.utils.DefaultNetworkListener$networkActor$1.invokeSuspend(DefaultNetworkListener.kt:131)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
    at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:37)
    at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:181)
    at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:91)
    at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:67)
    at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:173)
    at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:38)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3700)
    at android.app.ActivityThread.access$1700(ActivityThread.java:200)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1704)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:201)
    at android.app.ActivityThread.main(ActivityThread.java:6810)
    at java.lang.reflect.Method.invoke(Method.java:native)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

Logcat: 

--------- beginning of system
10-21 07:21:16.833  9472  9472 I Timeline: Timeline: Activity_launch_request time:2662840 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:21:17.889  9609  9609 I Timeline: Timeline: Activity_launch_request time:2663896 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:21:18.960  9723  9723 I Timeline: Timeline: Activity_launch_request time:2664968 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:21:20.074  9820  9820 I Timeline: Timeline: Activity_launch_request time:2666081 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:21:21.184  9912  9912 I Timeline: Timeline: Activity_launch_request time:2667192 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:21:22.325 10003 10003 I Timeline: Timeline: Activity_launch_request time:2668332 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:21:23.397 10095 10095 I Timeline: Timeline: Activity_launch_request time:2669404 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:21:24.423 10187 10187 I Timeline: Timeline: Activity_launch_request time:2670430 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:21:25.467 10279 10279 I Timeline: Timeline: Activity_launch_request time:2671474 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:21:27.180 10364 10364 I Timeline: Timeline: Activity_launch_request time:2673187 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:21:28.833 10461 10461 I Timeline: Timeline: Activity_launch_request time:2674840 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:21:59.944 10558 10558 I Timeline: Timeline: Activity_launch_request time:2705951 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:22:00.977 10756 10756 I Timeline: Timeline: Activity_launch_request time:2706984 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:22:02.026 10865 10865 I Timeline: Timeline: Activity_launch_request time:2708034 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:22:03.124 10961 10961 I Timeline: Timeline: Activity_launch_request time:2709131 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:22:04.213 11048 11048 I Timeline: Timeline: Activity_launch_request time:2710220 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
10-21 07:22:05.258 11138 11138 I Timeline: Timeline: Activity_launch_request time:2711265 intent:Intent { flg=0x10000000 cmp=com.github.sagernet.sagernet/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }

**Comment by feiyuang** [comment]
SagerNet 0.8.4 (823) OSS
Date: 2023-10-28 03:15:23.383 UTC

OS_VERSION: 4.4.153-perf+
SDK_INT: 28
RELEASE: 9
ID: PKQ1.180904.001
DISPLAY: PKQ1.180904.001
INCREMENTAL: V12.0.3.0.PEICNXM
SECURITY_PATCH: 2020-11-05
IS_DEBUGGABLE: 0
IS_EMULATOR: null
IS_TREBLE_ENABLED: true
TYPE: user
TAGS: release-keys

MANUFACTURER: Xiaomi
BRAND: xiaomi
MODEL: Redmi Note 5
PRODUCT: whyred
BOARD: sdm636
HARDWARE: qcom
DEVICE: whyred
SUPPORTED_ABIS: arm64-v8a, armeabi-v7a, armeabi

Settings: 

socksPort: 2080
portLocalDns: 6450
httpPort: 9080
transproxyPort: 9200
dnsHosts0: 
remoteDns: tcp://1.1.1.1
directDns: tcp://223.5.5.5
mtu: 1500
isAutoConnect: true
acquireWakeLock: false
appTheme: 2
nightTheme: 0
serviceMode: vpn
tunImplementation: 1
appTrafficStatistics: false
profileTrafficStatistics: true
speedInterval: 1000
alwaysShowAddress: false
securityAdvisory: true
meteredNetwork: false
showDirectSpeed: false
allowAccess: false
proxyApps: false
bypassLan: false
bypassLanInCoreOnly: false
domainStrategy: AsIs
trafficSniffing: true
destinationOverride: false
resolveDestination: false
ipv6Mode: 1
rulesProvider: 0
providerTrojan: 0
providerRootCA: 0
useLocalDnsAsDirectDns: false
enableDnsRouting: true
enableFakeDns: false
hijackDns: false
requireHttp: true
appendHttpProxy: true
requireTransproxy: false
transproxyMode: 0
connectionTestURL: https://www.google.com/generate_204
enableMux: false
enableMuxForAll: false
muxConcurrency: 8
tcpKeepAliveInterval: 15
enablePcap: false
enableLog: true
profileGroup: 1
profileId: 3
profileStarted: 0
profileCurrent: 0

Logcat: 

--------- beginning of system
10-28 11:03:27.480 24491 24491 W Looper  : Slow Looper main: Activity com.github.sagernet.sagernet/io.nekohasekai.sagernet.ui.MainActivity is 1535ms late (wall=238ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem }) because of 2 msg, msg 2 took 1529ms (late=11ms h=android.app.ActivityThread$H w=110)
10-28 11:03:35.275 24491 24491 I Timeline: Timeline: Activity_launch_request time:16424474 intent:Intent { cmp=com.android.vpndialogs/.ConfirmDialog }
10-28 11:03:49.016 24491 24491 W Looper  : Slow Looper main: doFrame is 307ms late because of 2 msg, msg 1 took 316ms (late=85ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
10-28 11:03:54.971 24491 24491 W Looper  : Slow Looper main: doFrame is 387ms late because of 29 msg, msg 1 took 400ms (late=119ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
10-28 11:04:29.430 24491 24491 W InputEventReceiver: Slow Input: took 114ms in dispatching, now at finishInputEvent (MotionEvent: event_seq=427, seq=27722, action=ACTION_MOVE)
10-28 11:04:47.012 24491 24491 W Looper  : Slow Looper main: doFrame is 346ms late because of 2 msg, msg 2 took 316ms (late=58ms h=android.os.Handler c=androidx.fragment.app.FragmentManager$5)
10-28 11:05:00.636 24491 24491 W Looper  : Slow Looper main: doFrame is 304ms late because of 1 msg, msg 1 took 391ms (late=1ms h=android.os.Handler c=kotlinx.coroutines.internal.DispatchedContinuation)
10-28 11:05:49.820 29713 29781 I Timeline: Timeline: Activity_launch_request time:16559019 intent:Intent { act=android.intent.action.CHOOSER (has extras) }
10-28 11:07:25.090 29713 29713 W InputEventReceiver: Slow Input: took 186ms in dispatching, now at finishInputEvent (MotionEvent: event_seq=458, seq=29613, action=ACTION_DOWN)
10-28 11:07:32.143 29713 31683 I Timeline: Timeline: Activity_launch_request time:16661342 intent:Intent { act=android.intent.action.CHOOSER (has extras) }
10-28 11:09:10.837  3415  3415 W InputEventReceiver: Slow Input: took 121ms in dispatching, now at finishInputEvent (MotionEvent: event_seq=31, seq=31431, action=ACTION_DOWN)
10-28 11:09:10.979  3415  3415 W InputEventReceiver: Slow Input: took 139ms in dispatching, now at finishInputEvent (MotionEvent: event_seq=36, seq=31457, action=ACTION_MOVE)
10-28 11:09:14.187  3415  3722 I Timeline: Timeline: Activity_launch_request time:16763386 intent:Intent { act=android.intent.action.CHOOSER (has extras) }
--------- beginning of main
10-28 11:15:14.205  3415  3722 W StatsBar$testConnection$1: 
10-28 11:15:14.205  3415  3722 W StatsBar$testConnection$1: android.os.DeadObjectException
10-28 11:15:14.205  3415  3722 W StatsBar$testConnection$1: 	at android.os.BinderProxy.transactNative(Native Method)
10-28 11:15:14.205  3415  3722 W StatsBar$testConnection$1: 	at android.os.BinderProxy.transact(Binder.java:1133)
10-28 11:15:14.205  3415  3722 W StatsBar$testConnection$1: 	at io.nekohasekai.sagernet.aidl.ISagerNetService$Stub$Proxy.urlTest(ISagerNetService.java:19)
10-28 11:15:14.205  3415  3722 W StatsBar$testConnection$1: 	at io.nekohasekai.sagernet.ui.MainActivity.urlTest(MainActivity.kt:24)
10-28 11:15:14.205  3415  3722 W StatsBar$testConnection$1: 	at io.nekohasekai.sagernet.widget.StatsBar$testConnection$1.invokeSuspend(StatsBar.kt:37)
10-28 11:15:14.205  3415  3722 W StatsBar$testConnection$1: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
10-28 11:15:14.205  3415  3722 W StatsBar$testConnection$1: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
10-28 11:15:14.205  3415  3722 W StatsBar$testConnection$1: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:79)
10-28 11:15:14.283  9684  9684 E net.sagernet:b: Not starting debugger since process cannot load the jdwp agent.
10-28 11:15:14.377  3415  3456 I gernet.sagerne: NativeAlloc concurrent copying GC freed 30407(1306KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 5MB/11MB, paused 186us total 101.399ms
10-28 11:15:14.398  9684  9684 I Perf    : Connecting to perf service.
10-28 11:15:14.436  9684  9684 W net.sagernet:b: Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (dark greylist, reflection)
10-28 11:15:14.446  9684  9684 W net.sagernet:b: Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (dark greylist, reflection)
10-28 11:15:14.447  9684  9684 W net.sagernet:b: Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (dark greylist, reflection)
10-28 11:15:14.461  9684  9684 W net.sagernet:b: Accessing hidden method Landroid/net/NetworkUtils;->protectFromVpn(I)Z (dark greylist, linking)
10-28 11:15:14.879  9684  9695 I net.sagernet:b: Background concurrent copying GC freed 16591(1725KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3MB/6MB, paused 1.514ms total 102.206ms
10-28 11:15:15.049  9684  9764 D v2ray-core: app/log: Logger started
10-28 11:15:15.053  9684  9764 D v2ray-core: app/dns: using mph domain matcher
10-28 11:15:15.057  9684  9742 D v2ray-core: app/proxyman/inbound: creating stream worker on 127.0.0.1:2080
10-28 11:15:15.057  9684  9742 D v2ray-core: app/proxyman/inbound: creating stream worker on 127.0.0.1:9080
10-28 11:15:15.057  9684  9742 D v2ray-core: app/proxyman/inbound: creating stream worker on 127.0.0.1:6450
10-28 11:15:15.057  9684  9742 D v2ray-core: app/stats: create new counter outbound>>>proxy-global-3>>>traffic>>>uplink
10-28 11:15:15.057  9684  9742 D v2ray-core: app/stats: create new counter outbound>>>proxy-global-3>>>traffic>>>downlink
10-28 11:15:15.057  9684  9742 D v2ray-core: app/stats: create new counter outbound>>>direct>>>traffic>>>uplink
10-28 11:15:15.057  9684  9742 D v2ray-core: app/stats: create new counter outbound>>>direct>>>traffic>>>downlink
10-28 11:15:15.057  9684  9742 D v2ray-core: app/stats: create new counter outbound>>>bypass>>>traffic>>>uplink
10-28 11:15:15.057  9684  9742 D v2ray-core: app/stats: create new counter outbound>>>bypass>>>traffic>>>downlink
10-28 11:15:15.057  9684  9742 D v2ray-core: app/stats: create new counter outbound>>>block>>>traffic>>>uplink
10-28 11:15:15.057  9684  9742 D v2ray-core: app/stats: create new counter outbound>>>block>>>traffic>>>downlink
10-28 11:15:15.057  9684  9742 D v2ray-core: app/stats: create new counter outbound>>>dns-out>>>traffic>>>uplink
10-28 11:15:15.057  9684  9742 D v2ray-core: app/stats: create new counter outbound>>>dns-out>>>traffic>>>downlink
10-28 11:15:15.058  9684  9684 D ProxyInstance: {
10-28 11:15:15.058  9684  9684 D ProxyInstance:   "dns": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:     "fallbackStrategy": "disabledIfAnyMatch",
10-28 11:15:15.058  9684  9684 D ProxyInstance:     "hosts": {},
10-28 11:15:15.058  9684  9684 D ProxyInstance:     "servers": [
10-28 11:15:15.058  9684  9684 D ProxyInstance:       {
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "address": "tcp://1.1.1.1",
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "domains": []
10-28 11:15:15.058  9684  9684 D ProxyInstance:       },
10-28 11:15:15.058  9684  9684 D ProxyInstance:       {
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "address": "tcp://223.5.5.5",
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "domains": [
10-28 11:15:15.058  9684  9684 D ProxyInstance:           "full:newstab.bygcloud.xyz"
10-28 11:15:15.058  9684  9684 D ProxyInstance:         ],
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "fallbackStrategy": "disabled"
10-28 11:15:15.058  9684  9684 D ProxyInstance:       }
10-28 11:15:15.058  9684  9684 D ProxyInstance:     ]
10-28 11:15:15.058  9684  9684 D ProxyInstance:   },
10-28 11:15:15.058  9684  9684 D ProxyInstance:   "inbounds": [
10-28 11:15:15.058  9684  9684 D ProxyInstance:     {
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "listen": "127.0.0.1",
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "port": 2080,
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "protocol": "socks",
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "settings": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "auth": "noauth",
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "udp": true
10-28 11:15:15.058  9684  9684 D ProxyInstance:       },
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "sniffing": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "destOverride": [
10-28 11:15:15.058  9684  9684 D ProxyInstance:           "http",
10-28 11:15:15.058  9684  9684 D ProxyInstance:           "tls",
10-28 11:15:15.058  9684  9684 D ProxyInstance:           "quic"
10-28 11:15:15.058  9684  9684 D ProxyInstance:         ],
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "enabled": true,
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "metadataOnly": false,
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "routeOnly": true
10-28 11:15:15.058  9684  9684 D ProxyInstance:       },
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "tag": "socks"
10-28 11:15:15.058  9684  9684 D ProxyInstance:     },
10-28 11:15:15.058  9684  9684 D ProxyInstance:     {
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "listen": "127.0.0.1",
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "port": 9080,
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "protocol": "http",
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "settings": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "allowTransparent": true
10-28 11:15:15.058  9684  9684 D ProxyInstance:       },
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "sniffing": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "destOverride": [
10-28 11:15:15.058  9684  9684 D ProxyInstance:           "http",
10-28 11:15:15.058  9684  9684 D ProxyInstance:           "tls",
10-28 11:15:15.058  9684  9684 D ProxyInstance:           "quic"
10-28 11:15:15.058  9684  9684 D ProxyInstance:         ],
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "enabled": true,
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "metadataOnly": false,
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "routeOnly": true
10-28 11:15:15.058  9684  9684 D ProxyInstance:       },
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "tag": "http"
10-28 11:15:15.058  9684  9684 D ProxyInstance:     },
10-28 11:15:15.058  9684  9684 D ProxyInstance:     {
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "listen": "127.0.0.1",
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "port": 6450,
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "protocol": "dokodemo-door",
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "settings": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "address": "1.0.0.1",
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "network": "tcp,udp",
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "port": 53
10-28 11:15:15.058  9684  9684 D ProxyInstance:       },
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "tag": "dns-in"
10-28 11:15:15.058  9684  9684 D ProxyInstance:     }
10-28 11:15:15.058  9684  9684 D ProxyInstance:   ],
10-28 11:15:15.058  9684  9684 D ProxyInstance:   "log": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:     "loglevel": "debug"
10-28 11:15:15.058  9684  9684 D ProxyInstance:   },
10-28 11:15:15.058  9684  9684 D ProxyInstance:   "outbounds": [
10-28 11:15:15.058  9684  9684 D ProxyInstance:     {
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "domainStrategy": "AsIs",
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "protocol": "shadowsocks",
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "settings": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "servers": [
10-28 11:15:15.058  9684  9684 D ProxyInstance:           {
10-28 11:15:15.058  9684  9684 D ProxyInstance:             "address": "1",
10-28 11:15:15.058  9684  9684 D ProxyInstance:             "method": "aes-128-gcm",
10-28 11:15:15.058  9684  9684 D ProxyInstance:             "password": "2",
10-28 11:15:15.058  9684  9684 D ProxyInstance:             "port": 3
10-28 11:15:15.058  9684  9684 D ProxyInstance:           }
10-28 11:15:15.058  9684  9684 D ProxyInstance:         ]
10-28 11:15:15.058  9684  9684 D ProxyInstance:       },
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "tag": "proxy-global-3"
10-28 11:15:15.058  9684  9684 D ProxyInstance:     },
10-28 11:15:15.058  9684  9684 D ProxyInstance:     {
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "protocol": "freedom",
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "tag": "direct"
10-28 11:15:15.058  9684  9684 D ProxyInstance:     },
10-28 11:15:15.058  9684  9684 D ProxyInstance:     {
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "protocol": "freedom",
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "tag": "bypass"
10-28 11:15:15.058  9684  9684 D ProxyInstance:     },
10-28 11:15:15.058  9684  9684 D ProxyInstance:     {
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "protocol": "blackhole",
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "tag": "block"
10-28 11:15:15.058  9684  9684 D ProxyInstance:     },
10-28 11:15:15.058  9684  9684 D ProxyInstance:     {
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "protocol": "dns",
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "proxySettings": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "tag": "proxy-global-3",
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "transportLayer": true
10-28 11:15:15.058  9684  9684 D ProxyInstance:       },
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "settings": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "address": "1.1.1.1",
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "network": "tcp",
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "port": 53,
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "userLevel": 1
10-28 11:15:15.058  9684  9684 D ProxyInstance:       },
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "tag": "dns-out"
10-28 11:15:15.058  9684  9684 D ProxyInstance:     }
10-28 11:15:15.058  9684  9684 D ProxyInstance:   ],
10-28 11:15:15.058  9684  9684 D ProxyInstance:   "policy": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:     "levels": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "1": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "connIdle": 30
10-28 11:15:15.058  9684  9684 D ProxyInstance:       }
10-28 11:15:15.058  9684  9684 D ProxyInstance:     },
10-28 11:15:15.058  9684  9684 D ProxyInstance:     "system": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "statsOutboundDownlink": true,
10-28 11:15:15.058  9684  9684 D ProxyInstance:       "statsOutboundUplink": true
10-28 11:15:15.058  9684  9684 D ProxyInstance:     }
10-28 11:15:15.058  9684  9684 D ProxyInstance:   },
10-28 11:15:15.058  9684  9684 D ProxyInstance:   "routing": {
10-28 11:15:15.058  9684  9684 D ProxyInstance:     "domainStrategy": "AsIs",
10-28 11:15:15.058  9684  9684 D ProxyInstance:     "rules": [
10-28 11:15:15.058  9684  9684 D ProxyInstance:       {
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "inboundTag": [
10-28 11:15:15.058  9684  9684 D ProxyInstance:           "dns-in"
10-28 11:15:15.058  9684  9684 D ProxyInstance:         ],
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "outboundTag": "dns-out",
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "type": "field"
10-28 11:15:15.058  9684  9684 D ProxyInstance:       },
10-28 11:15:15.058  9684  9684 D ProxyInstance:       {
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "outboundTag": "dns-out",
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "protocol": [
10-28 11:15:15.058  9684  9684 D ProxyInstance:           "dns"
10-28 11:15:15.058  9684  9684 D ProxyInstance:         ],
10-28 11:15:15.058  9684  9684 D ProxyInstance:         "type": "field"
10-28 11:15:15.058  9684  9684 D ProxyInstance:       }
10-28 11:15:15.058  9684  9684 D ProxyInstance:     ]
10-28 11:15:15.058  9684  9684 D ProxyInstance:   },
10-28 11:15:15.058  9684  9684 D ProxyInstance:   "stats": {}
10-28 11:15:15.058  9684  9684 D ProxyInstance: }
10-28 11:15:15.086  9684  9742 I v2ray-core: transport/internet/tcp: listening TCP on 127.0.0.1:2080
10-28 11:15:15.086  9684  9707 I v2ray-core: transport/internet/udp: listening UDP on 127.0.0.1:2080
10-28 11:15:15.086  9684  9707 I v2ray-core: transport/internet/tcp: listening TCP on 127.0.0.1:9080
10-28 11:15:15.086  9684  9707 I v2ray-core: transport/internet/tcp: listening TCP on 127.0.0.1:6450
10-28 11:15:15.087  9684  9742 I v2ray-core: transport/internet/udp: listening UDP on 127.0.0.1:6450
10-28 11:15:15.087  9684  9742 W v2ray-core: V2Ray 5.10.0 started
10-28 11:15:15.097  9684  9708 I libcore : updated root ca certificate list
10-28 11:15:15.130  9684  9708 D v2ray-core: libcore/nat: tcp forwarder started at [::]:41719
10-28 11:15:15.161  9684  9684 D libcore : updated network type: wifi
10-28 11:15:15.173  9684  9684 D libcore : updated wifi ssid: <unknown ssid>
10-28 11:15:16.015  9684  9705 I v2ray-core: libcore/nat: dispatch tcp conn failed > accept tcp [::]:41719: use of closed network connection
10-28 11:15:16.115  9684  9705 D v2ray-core: app/log: Logger closing
10-28 11:15:22.404  9684  9701 I net.sagernet:b: ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000

**Comment by feiyuang** [comment]
弹DeadObjectException 错误提示 无限开关

**Comment by feiyuang** [comment]
原版和其他fork 无此问题 日志抓取只能抓到上面那些

**Comment by aviraxp** [comment]
我也复现这个问题了，我这里是把mtu设成32000就能复现
